// Records every name the app puts into the shared scope.
//
// tests/app-boot.test.js compares the live app against the file this writes. The point is to notice
// a name that disappeared or changed kind, which is the way a refactor breaks things quietly: the
// page still loads, and then one button does nothing because the function behind it is gone.
//
// Run this when a change to that list is deliberate, and read the diff before committing it.
//
//   node tools/record-globals.js

const fs = require('fs');
const path = require('path');
const { bootApp, globalsDefined, globalKinds } = require('./loadapp');

const OUT = path.join(__dirname, '..', 'tests', 'expected-globals.json');

(async () => {
    const app = await bootApp();

    if (app.problems.length) {
        app.problems.forEach((p) => console.error(`could not load ${p.file}: ${p.error.message}`));
        process.exit(1);
    }
    if (app.failures.length) {
        app.failures.forEach((error) => console.error(`start up failed: ${error.message}`));
        process.exit(1);
    }

    const names = globalsDefined(app);
    const kinds = globalKinds(app, names);

    const record = {
        note: 'Every name the app puts into the shared scope, and what kind of thing it is. '
            + 'Generated by tools/record-globals.js and checked by tests/app-boot.test.js. '
            + 'If this file changed and you did not mean it to, something was renamed or lost.',
        count: names.length,
        names: names.map((name) => `${name}: ${kinds[name]}`),
    };

    fs.writeFileSync(OUT, `${JSON.stringify(record, null, 1)}\n`);
    console.log(`recorded ${names.length} names into ${path.relative(process.cwd(), OUT)}`);
})();
